[build]
 functions = "functions"

[functions]
node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to="/.netlify/functions/api/:splat"
  status=200

[[headers]]
  for = "/*"
  [headers.values]
    access-control-allow-origin = "*"